### PR TITLE
Various bug fixes and improvements

### LINKED ISSUE #59: Raise doesn't always work the first time.
Maybe raising in a delay loop until either hitting an error or getting an updated window list?

I think this happened less often when AX caching was enabled, but can't be sure.

### LINKED ISSUE #105: Selector is not tracking the selected window when it is raised?
The implementation work for #104 includes some work to make #59 easier in that the state machine will deactivate when it gets a `windowList` where the application of the first window is active and the first window matches the `selectedWindow`.

Unfortunately, it doesn't work—the selector maintains its `selectedIndex` instead of tracking the movement of the window. I suspect something odd is going on with equality testing of window objects. For now, the state machine has a hack (look for comments with this issue number in `SWCoreWindowService.m` and `SWStateMachine.m`) that preserves the pre-refactor behaviour.

### LINKED ISSUE #121: Window content workers being leaked somewhere
Not sure how, but there's definitely instances of `SWWindowWorker` polling for window contents long after the interface has been dismissed.

### PR DESCRIPTION
**Pull request by numist**
This branch got away from me a little bit.
- Fixes #59 - Raise doesn't always work the first time.
- Fixes #105 - Selector is not tracking the selected window when it is raised?
- Fixes #121 - Window content workers being leaked somewhere
- Better naming for dispatch queues
- Better CocoaPods configuration
- Interface does not show if raise is requested before the display timer has fired
- Thumbnails delay updates at first to reduce system load

### CODE REVIEW

File: Switch/SWCoreWindowService.m [hunk 1]
```diff
@@ -373,8 +368,11 @@ - (void)private_displayTimerFired:(NSTimer *)timer;
         return;
     }
 
-    [self.stateMachine displayTimerCompleted];
-    self.displayTimer = nil;
+    // Do not show the interface if the state machine has an action pending.
+    if (!self.stateMachine.pendingSwitch) {
+        [self.stateMachine displayTimerCompleted];
+        self.displayTimer = nil;
+    }
```
Comment (numist) [inline Switch/SWCoreWindowService.m]: This stuff should be factored into the state machine. It's conditional on the state machine's state, and is intended to modify a state machine action (displaying the interface).

File: Switch/SWCoreWindowService.m [hunk 2]
```diff
@@ -404,4 +399,40 @@ - (void)private_hideInterface;
...
+        if (error) {
+            SWLog(@"Failed to raise window group %@: %@", selectedWindow, error);
+        }
+        
+        NSOrderedSet *windowList = self.stateMachine.windowList;
+        NSUInteger selectedIndex = [windowList indexOfObject:selectedWindow];
+
+        if (selectedIndex == 0) {
+            // If the selected index was 0, this action won't change the window order so this code must replay the last update event.
+            [self.stateMachine updateWindowList:self.stateMachine.windowList];
```
Comment (numist) [inline Switch/SWCoreWindowService.m:419]: In an ideal world, this will break when #122 gets fixed, as `activeApplication` should become an immutable data property.

Unfortunately, `refreshWindowList` won't dispatch a notification if there is only a change in active application, so that'll have to happen later. Sorry, future me.
