### PR TITLE
Fix #68.

### LINKED ISSUE #68: Crash in SWAppDelegate relaunch:?
Looks like `SWAppDelegate relaunch:` has been crashing for people.

Reporting says:

```
Fatal Exception: NSInvalidArgumentException
*** -[NSFileManager copyItemAtPath:toPath:error:]: source path is nil
```

### PR DESCRIPTION
**Pull request by numist**
Switch was using the relaunch mechanism built into Sparkle, which changed between the current shipping binary and the top of master, which Switch started using in 0.0.7. This ultimately meant I traded a corrupted code signature for a crash on the very first launch. Oops.

Switch now includes its own relaunch mechanism, which is a (minor) rewrite of Sparkle's old relauncher.

### CODE REVIEW

File: relaunch/TerminationListener.m [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+
+- (id)initWithExecutablePath:(const char *)execPath parentProcessId:(pid_t)ppid;
+{
+	self = [super init];
+	if (self != nil)
+	{
+		_executablePath = execPath;
+		_parentProcessId = ppid;
+		if (getppid() == 1) {
+            // ppid is launchd (1) => parent terminated already
```
Comment (numist) [inline relaunch/TerminationListener.m]: Are there mixed tabs and spaces in this file?
